format = """
$directory\
$git_branch\
$git_status\
$git_state\
$custom\
$aws\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "bold blue"
truncation_length = 1

[git_branch]
symbol = " "
style = "bold purple"
truncation_length = 30
format = '[$symbol$branch]($style) '

[aws]
format = '[$symbol($profile )(\[$duration\] )]($style)'
symbol = '󰅟  '
style = "bold yellow"
force_display = false

[time]
disabled = false
time_format = "%T"
utc_time_offset = "+2"
style = "bold purple"
format = '[  $symbol$time]($style) '

[cmd_duration]
format = '[  $duration]($style) '
style = 'bold green'

